import { Product, Coupon, Review, Promotion } from './types';

export const BRAND_INFO = {
  name: 'FAST Burgerz',
  owner: 'M. D. M. Irfan',
  address: 'Second Home Boys Hostel, Near Soneri Bank, Bherapul, Bharakahu, Islamabad, Pakistan',
  whatsappNumber: '+923409631937',

  contactNumbers: ['03409631937', '03465177174'],
  deliveryEstimate: '20–40 Minutes',
  deliveryCharges: 80,
  minDeliveryOrder: 300,
  freeDeliveryThreshold: 1500,
  businessHours: '4:00 PM - 4:00 AM',
};

export const INITIAL_PRODUCTS: Product[] = [
  // Burgers
  {
    id: 'b1',
    name: 'Jalapeno Beef Burger',
    price: 470,
    category: 'burgers',
    description: 'Fresh beef patty grilled to perfection, topped with spicy pickled jalapenos, melted cheese, and our signature fiery burger sauce inside a brioche bun.',
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    isPopular: true,
    tags: ['Beef', 'Spicy', 'Best Seller'],
  },
  {
    id: 'b2',
    name: 'Beef Smash Burger (Regular)',
    price: 450,
    category: 'burgers',
    description: 'Smashed house beef patty crispy-edged on the flat top, layered with American cheese slices, dill pickles, onions, and classic burger sauce.',
    image: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    isPopular: false,
    tags: ['Beef', 'Classic'],
  },
  {
    id: 'b3',
    name: 'Beef Smash Burger (Special)',
    price: 650,
    category: 'burgers',
    description: 'Double smashed beef patties with double melted cheese, grilled mushrooms, caramelized onions, house special sauce, served fresh and warm.',
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    isPopular: true,
    isNew: true,
    tags: ['Double Beef', 'Premium'],
  },
  {
    id: 'b4',
    name: 'Zinger Burger',
    price: 400,
    category: 'burgers',
    description: 'Golden, crispy hand-breaded chicken breast fillet fried to crunch perfection, drizzled with creamy mayo and fresh shredded lettuce.',
    image: 'https://images.unsplash.com/photo-1625813506062-0aeb1d7a094b?w=600&auto=format&fit=crop&q=80',
    rating: 4.7,
    isPopular: true,
    tags: ['Chicken', 'Crispy'],
  },
  {
    id: 'b5',
    name: 'Wahshi Zinger Burger',
    price: 650,
    category: 'burgers',
    description: 'The monumental beast! Double crispy zinger chicken patties, layered with thick melted cheese, jalapeno pepper rings, and spicy Wahshi chili mayo.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyU9PaA5jJ7smRhCLWFQFy0o9amfqtGRMYoTWAm_MvVQ&s=10',
    rating: 4.9,
    isPopular: true,
    tags: ['Double Chicken', 'Gigantic', 'Spicy'],
  },
  {
    id: 'b6',
    name: 'Chicken Grill Burger',
    price: 450,
    category: 'burgers',
    description: 'Flame-grilled marinated chicken breast fillet, served with sliced tomatoes, crisp red onions, lettuce, and a light smokey mustard mayo sauce.',
    image: 'https://images.unsplash.com/photo-1521305916504-4a1121188589?w=600&auto=format&fit=crop&q=80',
    rating: 4.5,
    tags: ['Chicken', 'Grilled', 'Healthy Choice'],
  },
  {
    id: 'b7',
    name: 'Chicken Grill Burger Special',
    price: 650,
    category: 'burgers',
    description: 'Premium grilled chicken breast fillet smothered in melted cheddar, customized premium herb spices, layered with sautéed bell peppers and garlic-aioli squeeze.',
    image: 'https://stock.adobe.com/search?k=grill+chicken+burger',
    rating: 4.8,
    isNew: true,
    tags: ['Grilled', 'Exclusive', 'Premium'],
  },

  // Fries
  {
    id: 'f1',
    name: 'Plain Fries',
    price: 120,
    category: 'fries',
    description: 'Classic salted hand-cut crisp golden French fries, fried to perfection and seasoned with our home-made seasoning. Ideal savory side.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRi0KO8uz6QJvyzsjQl608QpSjzNRdbNSGr3g&s',
    rating: 4.3,
    tags: ['Classic', 'Vibe'],
  },
  {
    id: 'f2',
    name: 'Garlic Mayo Fries',
    price: 150,
    category: 'fries',
    description: 'Our golden fries loaded with a rich dressing of customized creamy home-made garlic powder mayo and a sprinkling of minced parsley.',
    image: 'https://static.tossdown.com/images/cd443e3c-2599-46fb-8818-7f2b21841cd0.webp',
    rating: 4.6,
    isPopular: true,
    tags: ['Creamy', 'Garlic'],
  },
  {
    id: 'f3',
    name: 'Loaded Fries',
    price: 550,
    category: 'fries',
    description: 'A colossal bowl of crispy fries smothered in melted hot dynamic cheese sauce, shredded chicken chunk tidbits, jalapeno rings, and dynamic herbs.',
    image: 'https://images.unsplash.com/photo-1585109649139-366815a0d713?w=600&auto=format&fit=crop&q=80',
    rating: 4.9,
    isPopular: true,
    tags: ['Loaded', 'Cheesy', 'Meal Size'],
  },

  // Wraps & Shawarma
  {
    id: 'w1',
    name: 'Zinger Wrap',
    price: 420,
    category: 'wraps',
    description: 'Crispy structural golden zinger chicken strips wrapped in a warm soft tortilla, tossed with dynamic pepper mayo, crisp green cabbage and fresh lettuce.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRyU9PaA5jJ7smRhCLWFQFy0o9amfqtGRMYoTWAm_MvVQ&s=10',
    rating: 4.7,
    isPopular: true,
    tags: ['Crispy Chicken', 'Wrap'],
  },
  {
    id: 'w2',
    name: 'Shawarma',
    price: 200,
    category: 'wraps',
    description: 'Authentic local chicken shawarma rolled in flatbread with traditional spicy red sauce, creamy tahini style mayo spread, and pickled cucumber strips.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSVjYIeoqAt7-ueX_9K9L0OFEmfZJvXJoow0Y6oNBg8Uw&s=10',
    rating: 4.8,
    isPopular: true,
    tags: ['Traditional', 'Value Deal'],
  },

  // Wings
  {
    id: 'ng1',
    name: 'Crispy Wings (6 pcs)',
    price: 350,
    category: 'wings',
    description: 'Six piece crunchy hand-battered chicken wings fried to structural perfection, sprinkled with a touch of local spices and served with visual savory-dip sauce.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80',
    rating: 4.6,
    tags: ['Appetizer', 'Crispy'],
  },
  {
    id: 'ng2',
    name: 'Crispy Wings (12 pcs)',
    price: 700,
    category: 'wings',
    description: 'Twelve piece ultimate party portion chicken wings, dry-crunchy or tossed lightly with dipping sauce. Best shared with boys.',
    image: 'https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=600&auto=format&fit=crop&q=80',
    rating: 4.8,
    tags: ['Party Size', 'Crunchy'],
  },

  // Sandwich
  {
    id: 'sd1',
    name: 'Club Sandwich',
    price: 370,
    category: 'sandwiches',
    description: 'Triple decker classic toasted sandwich containing loaded chicken breast chunks, fried egg layers, fresh sliced tomatoes, lettuce, cucumber slice grids, and light sandwich mayo.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-9vJdtM4KzbRVGylTph9l_F48ISJ_OjRpew&s',
    rating: 4.4,
    tags: ['Toasted', 'Filling'],
  },

  // Drinks
  {
    id: 'dr1',
    name: 'Mint Margarita',
    price: 150,
    category: 'drinks',
    description: 'Wonderfully chilled summer absolute refresher blend of cool ice, sparkling soda, sweet citrus juice, and freshly ground vibrant green organic mint leaves.',
    image: 'https://static.tossdown.com/images/a18d1984-8640-45b2-93e0-c5ff60ada1ee.webp',
    rating: 4.7,
    isPopular: true,
    tags: ['Ice Cold', 'Cooling'],
  },
  {
    id: 'dr2',
    name: 'Lemon Soda',
    price: 120,
    category: 'drinks',
    description: 'Sparkling aerated water mixed with direct freshly squeezed lemon pulp and dynamic local rock salt, served in an overflowing glass of crushed ice cubes.',
    image: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcThPSh2Up2fS6SnvtiaNLFJI8OXOQoNbGfSCg&s',
    rating: 4.5,
    tags: ['Bubbly', 'Refreshing'],
  },
];

export const INITIAL_COUPONS: Coupon[] = [
  {
    code: 'WELCOME50',
    discountType: 'fixed',
    discountValue: 50,
    minAmount: 300,
    description: 'Rs. 50 off your first online order!',
  },
  {
    code: 'FASTWEEKEND',
    discountType: 'percentage',
    discountValue: 10,
    minAmount: 800,
    description: '10% discount on order above Rs. 800 this weekend.',
  },
  {
    code: 'HOSTELDEAL',
    discountType: 'fixed',
    discountValue: 100,
    minAmount: 1000,
    description: 'Rs. 100 off for orders above Rs. 1000! Perfect for Hostels.',
  },
];

export const SPECIAL_OFFERS = [
  {
    id: 'o1',
    title: 'Buy 2 Burgers, Get FREE Fries!',
    description: 'Order any two delicious burgers from our menu and automatically get complimentary crunchy golden fries included with your meal packet.',
    terms: 'Valid on both beef and chicken burgers.',
    icon: '🍟',
  },
  {
    id: 'o2',
    title: 'Flat 10% Student Discount',
    description: 'Are you living in Soneri Bank area hostels or studying nearby? Enjoy an exclusive 10% discount on any wrap, shawarma, or zinger order.',
    terms: 'Show student card at doorstep delivery or enter code STUDENT10.',
    icon: '🎓',
  },
  {
    id: 'o3',
    title: 'Hostel Night Owls Special',
    description: 'Get free deliveries directly to your hostel room stairs after 11:00 PM for orders over Rs. 500. No deliveries charges applied.',
    terms: 'Valid around Bharakahu hostel circles.',
    icon: '🌙',
  },
  {
    id: 'o4',
    title: 'Weekend Family / Friends Combo Deal',
    description: 'Buy 1 Double Beef Smash Special + 1 Wahshi Zinger + Loaded Fries + 2 Margaritas for only Rs. 1800 (Save Rs. 200).',
    terms: 'Order online on Friday, Saturday & Sunday.',
    icon: '🍔',
  },
];

export const PROMOTION_BANNERS: Promotion[] = [
  {
    id: 'p1',
    title: "TODAY'S SPECIAL OFFER",
    description: 'Get FREE Fries on purchase of any 2 Burgers!',
    badge: 'Limited Offer',
    bgImage: 'https://images.unsplash.com/photo-1594212699903-ec8a3eca50f5?w=1000&auto=format&fit=crop&q=80',
  },
  {
    id: 'p2',
    title: 'WEEKEND SMASH BONANZA',
    description: '10% Off on all Smashed Beef Burger Platters above Rs. 800',
    badge: 'Promo: FASTWEEKEND',
    code: 'FASTWEEKEND',
    bgImage: 'https://images.unsplash.com/photo-1550547660-d9450f859349?w=1000&auto=format&fit=crop&q=80',
  },
  {
    id: 'p3',
    title: 'NEW MONSTER ARRIVAL',
    description: 'Meet the Wahshi Zinger - Double stack chicken with Wahshi chili sauce',
    badge: 'Chili Spicy 🔥',
    bgImage: 'https://images.unsplash.com/photo-1626700051175-6518c4793f4f?w=1000&auto=format&fit=crop&q=80',
  },
  {
    id: 'p4',
    title: 'THE BOYS FEAST COMBO',
    description: '2 Zinger Wraps + Loaded Fries + 2 Lemon Sodas for only Rs. 1400',
    badge: 'Save 15%',
    bgImage: 'https://images.unsplash.com/photo-1541532713592-79a0317b6b77?w=1000&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'r1',
    name: 'Hamza Malik',
    rating: 5,
    comment: 'The Wahshi Zinger Burger is literally out of this world! Massive chicken portion, crispy exterior, and the spice level is perfectly customizable. Living in Second Home Hostel, we order this almost every lock-in night! Highly recommended!',
    date: '2 Days ago',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?w=100&auto=format&fit=crop&q=80',
    tag: 'Hostel Resident',
  },
  {
    id: 'r2',
    name: 'Zainab Qazi',
    rating: 5,
    comment: 'Extremely fresh and top-notch hygiene! The Jalapeno Beef Smash is juicy, with perfectly smashed thin edges. Mint Margarita is perfect refreshment on hot days. Delivery was extremely fast, took only 25 minutes to our location.',
    date: '1 Week ago',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=100&auto=format&fit=crop&q=80',
    tag: 'Verified Diner',
  },
  {
    id: 'r3',
    name: 'Daniyal Ahmed',
    rating: 4.8,
    comment: 'Solid price-to-portion value. Plain Shawarma is super authentic, and Garlic Mayo Fries are thick and creamy. Excellent delivery service by M. D. M. Irfan’s team directly to Bherapul Soneri Bank area. Will order again!',
    date: '3 Days ago',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&auto=format&fit=crop&q=80',
    tag: 'Regular Customer',
  },
];
